package dev.isaaccmedeiros;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class StarterTest {
    @Test void appHasAGreeting() {
        Starter classUnderTest = new Starter();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
